server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vprojecte_account_data
    username: letmein
    password: letmein
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/vprojecte-main-realm
          jwk-set-uri: http://localhost:8080/realms/vprojecte-main-realm/protocol/openid-connect/certs