spring:
  application:
    name: vprojecte-api-server
  config:
    import: configserver:http://localhost:8888
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  profiles:
    active:
      - microservice
      - kc
      - kafka-vprojecte-main