server:
  port: 8888

spring:
  application:
    name: vprojecte-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YourPal93/vprojecte-config-repo.git
          clone-on-start: true
          basedir: file://c:/tools/vprojecte-git-c
          default-label: main
  profiles:
    active:
      - secret
