server:
  port: 8888

spring:
  application:
    name: vprojecte-config-server
  cloud:
    config:
      server:
        git:
          uri:
          clone-on-start:
          basedir:
          username:
          password:
          default-label: main
