spring:
  application:
    name: monolith-current
  config:
    import: configserver:http://localhost:8888
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active:
      - microservice
      - mysql-vprojecte
  mail:
    host: smtp.mail.ru
    username: vprojecte.noreply@mail.ru
    password: QYYcxubPDQ6MuAWmKxf0
    port: 465
    protocol: smtps
    properties:
      smtp:
        auth: true

mail:
  debug: true