server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vprojecte
    username: letmein
    password: letmein
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.mail.ru
    username: vprojecte.noreply@mail.ru
    password: QYYcxubPDQ6MuAWmKxf0
    port: 465
    protocol: smtps
    properties:
      smtp:
        auth: true

mail:
  debug: true

jwt:
  secret: lasdjflsakjdf;laksjdfls&*%@kdjaf@@TemporaryKeyForJwtasd235kjf;l%$@askjdfl;sakjdf

management:
  server:
    port: 8091
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true